# Thank you for downloading EnhancedHomes!
# This plugin was created by Noma (@nohmah) and rvHoney (@rvhoney) for EnhancedPlugins.
# If you have any questions or suggestions, feel free to contact us on SpigotMC or Discord.
# Permissions are prioritized over the default configuration.

# Cross-world teleportation (true/false)
cross-world-tp: false

# Teleportation warmup (true/false and time in seconds)
warmup: true
warmup-time: 5

# Limit on number of homes (true/false and max number of homes)
home-limit: false
max-homes: 10